### ISSUE TITLE
Infinite loop on npm start when custom port in use and port is unavailable

### ISSUE THREAD

**Issue by kaladay** [TAMULib/Weaver-UI-Core#159]
When a port is explicitly specified, such as: `wvr server -p 8181 -b /myapp --prod --uid myapp`, and another server, such as apache, is already using that port, then it infinitely tries to start.

Furthermore, there is no delay in this restart and it runs as fast as it can, potentially causing CPU performance problems.

```
Error: listen EADDRINUSE :::8181
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/xxx/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/xxx/node_modules/@wvr/core/weaver-webserver.js:32:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
2020-05-21 13:27:12: Forever detected script exited with code 1
2020-05-21 13:27:12: Forever restarting script for 22 time
2020-05-21 13:27:12 Server now running at pid: 3511
events.js:183
      throw er; // Unhandled 'error' event
      ^
```

**Comment by kaladay** [comment]
This shouldn't matter any more once we migrate to webpack so I am closing this.
